spring:
  datasource:
    url: jdbc:postgresql://db.forage.com:5432/forage_db
    username: serveradmin
    password: server123
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    generate-ddl: true

files:
  storage:
    path: /opt/resources/files
server:
  name: http://110.74.194.123:6754