spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5779/forage_db
    username: serveradmin
    password: server123
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
files:
  storage:
    path: src/main/resources/uploads
#    path: /opt/resources/files
server:
  name: http://localhost:8080